In [12]:
%pip list


Package                      Version
---------------------------- --------
absl-py                      1.4.0
asttokens                    2.2.1
attrs                        22.2.0
autopep8                     2.0.2
backcall                     0.2.0
colorama                     0.4.6
comm                         0.1.2
comtypes                     1.1.14
contourpy                    1.0.7
cycler                       0.11.0
debugpy                      1.6.6
decorator                    5.1.1
executing                    1.2.0
flatbuffers                  23.3.3
fonttools                    4.39.0
ipykernel                    6.21.3
ipython                      8.11.0
jedi                         0.18.2
jupyter_client               8.0.3
jupyter_core                 5.2.0
kiwisolver                   1.4.4
libclang                     16.0.0
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mediapipe                    0.9.1.0
nest-asyncio                 1.5.6
nump


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
%pip install tensorflow


  Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
  Using cached tensorflow_intel-2.12.0-cp310-cp310-win_amd64.whl (272.8 MB)
  Using cached grpcio-1.54.2-cp310-cp310-win_amd64.whl (4.1 MB)
  Using cached tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
  Using cached jax-0.4.11-py3-none-any.whl
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached h5py-3.8.0-cp310-cp310-win_amd64.whl (2.6 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached scipy-1.10.1-cp310-cp310-win_amd64.whl (42.5 MB)
  Using cached ml_dtypes-0.2.0-cp310-cp310-win_amd64.whl (938 kB)
  Using cached Werkzeug-2.3.5-py3-none-any.whl (242 kB)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
  Using cached google_auth-2.19.1-py2.py3-none-any.whl (181 kB)
  Using cached requ


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import cv2
import os
import random
import numpy as np
from matplotlib import pyplot as plt

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer,Conv2D,Dense,MaxPooling2D, Input, Flatten


In [3]:
# Avoid OOM errors by setting GPU Memory Consumption Growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [7]:

# Setup paths
POS_PATH = os.path.join('data', 'positive')
NEG_PATH = os.path.join('data', 'negative')
ANC_PATH = os.path.join('data', 'anchor')

In [5]:

# Make the directories
os.makedirs(POS_PATH)
os.makedirs(NEG_PATH)
os.makedirs(ANC_PATH)

In [9]:
# http://vis-www.cs.umass.edu/lfw/
# Uncompress Tar GZ Labelled Faces in the Wild Dataset
!tar -xf lfw.tgz

In [10]:
# Move LFW Images to the following repository data/negative
for directory in os.listdir('lfw'):
    for file in os.listdir(os.path.join('lfw', directory)):
        EX_PATH = os.path.join('lfw', directory, file)
        NEW_PATH = os.path.join(NEG_PATH, file)
        os.replace(EX_PATH, NEW_PATH)


# Collecting Data

In [4]:
import uuid

In [29]:
num_anchors=3000
num_pos=3000

In [30]:
cam=cv2.VideoCapture(0)

captured=0

#Capturing anchors in user friendly way
while True:
    check, frame = cam.read()

    if (cv2.waitKey(1) & 0XFF) == ord('q'):
        break

    if(check and captured<num_anchors):

        cv2.imshow('Image Collection', frame)
        frame = frame[120:120+250, 200:200+250]
        path = os.path.join(ANC_PATH, str(uuid.uuid1())+'.jpg')
        cv2.imwrite(path, frame)
        captured+=1
    

cam.release()
cv2.destroyAllWindows()


In [31]:
cam = cv2.VideoCapture(0)

captured = 0

# Capturing positives in user friendly way only issue is that the frame freezes aftetr taking 300 pics
while True:
    check, frame = cam.read()

    if (cv2.waitKey(1) & 0XFF) == ord('q'):
        break

    if (check and captured < num_anchors): #we can give a pop up once this is done.

        cv2.imshow('Image Collection', frame)
        frame = frame[120:120+250, 200:200+250]
        path = os.path.join(POS_PATH, str(uuid.uuid1())+'.jpg')
        cv2.imwrite(path, frame)
        captured += 1


cam.release()
cv2.destroyAllWindows()


In [18]:
# cam=cv2.VideoCapture(0)

# while True:
#     check,frame=cam.read()

#     cv2.imshow('Image Collection', frame)

#     frame=frame[120:120+250,200:200+250]   
    
#     #need to add gridlines in image frame so that people only keep their face in this region of their frame

#     if (cv2.waitKey(1) & 0XFF) == ord('q'):
#         break

#     if (cv2.waitKey(1) & 0XFF) == ord('a'):  
#         #have to find a way to modify this and make it more user friendly, instead of making user capture 300 images.

#         path = os.path.join(ANC_PATH, str(uuid.uuid1())+'.jpg')
#         cv2.imwrite(path, frame)

#     if (cv2.waitKey(1) & 0XFF) == ord('p'):
#         # have to find a way to modify this and make it more user friendly, instead of making user capture 300 images.

#         path = os.path.join(POS_PATH, str(uuid.uuid1())+'.jpg')
#         cv2.imwrite(path, frame)

# cam.release()
# cv2.destroyAllWindows()

# Creating Labelled Dataset

In [32]:
def preprocess(file_path):

    byte_img = tf.io.read_file(file_path)
    # Load in the image
    img = tf.io.decode_jpeg(byte_img)

    img = tf.image.resize(img, (105, 105))
    # Scale image to be between 0 and 1
    img = img / 255.0
    return img


In [35]:
import glob


In [36]:
anchor = tf.data.Dataset.from_tensor_slices(glob.glob(ANC_PATH+'\*.jpg')).take(3000)
positive = tf.data.Dataset.from_tensor_slices(glob.glob(POS_PATH+'\*.jpg')).take(3000)
negative = tf.data.Dataset.from_tensor_slices(glob.glob(NEG_PATH+'\*.jpg')).take(3000)

# Converting all the data into tensorflow dataset

In [40]:
anchor.map(preprocess)
positive.map(preprocess)
negative.map(preprocess)

#Preprocessing all the image data

<_MapDataset element_spec=TensorSpec(shape=(105, 105, None), dtype=tf.float32, name=None)>

In [45]:
dataset_pos=tf.data.Dataset.zip((anchor,positive,tf.data.Dataset.from_tensor_slices(tf.ones(len(anchor)))))
dataset_neg=tf.data.Dataset.zip((anchor,negative,tf.data.Dataset.from_tensor_slices(tf.zeros(len(anchor)))))


In [122]:
dataset=dataset_pos.concatenate(dataset_neg)
dataset=dataset.shuffle(buffer_size=len(anchor))


In [126]:
for data in dataset:
    print(data)

#testing out the dataset formation 

(<tf.Tensor: shape=(), dtype=string, numpy=b'data\\anchor\\783779bb-0900-11ee-bb1d-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'data\\positive\\c4f16c85-0900-11ee-8afb-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'data\\anchor\\9d99b33f-0900-11ee-a40b-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'data\\positive\\ea08e5c5-0900-11ee-beae-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'data\\anchor\\9ffc25c7-0900-11ee-abb4-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'data\\positive\\ec6c96b6-0900-11ee-b1c1-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'data\\anchor\\74575391-0900-11ee-adf0-f889d2136612.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'data\\positive\\c123bacd-0900-11ee-9158-f889d2136612.jpg'>, <tf.Tensor: shape=(), dty

In [130]:
dataset_train=dataset.take(int(0.7*len(dataset)))
dataset_test=dataset.skip(int(0.7*len(dataset)))


print(len(dataset_test))
print(len(dataset_train))
print(len(dataset))


1800
4200
6000
